<?php

function profile_photo_store(array $file): ?string
{
    $error = $file['error'] ?? UPLOAD_ERR_NO_FILE;
    if ($error === UPLOAD_ERR_NO_FILE) return null;
    if (in_array($error, [UPLOAD_ERR_INI_SIZE, UPLOAD_ERR_FORM_SIZE], true)) {
        throw new RuntimeException('รูปโปรไฟล์ต้องมีขนาดไม่เกิน 5 MB');
    }
    if ($error !== UPLOAD_ERR_OK || !is_string($file['tmp_name'] ?? null) || !is_uploaded_file($file['tmp_name'])) {
        throw new RuntimeException('อัปโหลดรูปไม่สำเร็จ กรุณาเลือกรูปใหม่');
    }
    $path = $file['tmp_name'];
    if (filesize($path) > 5 * 1024 * 1024) throw new RuntimeException('รูปโปรไฟล์ต้องมีขนาดไม่เกิน 5 MB');
    $info = @getimagesize($path);
    $mime = mime_content_type($path);
    if (!$info || !in_array($mime, ['image/jpeg', 'image/png', 'image/webp'], true) || $info['mime'] !== $mime) {
        throw new RuntimeException('กรุณาเลือกรูป JPG, PNG หรือ WebP เท่านั้น');
    }
    if ($info[0] * $info[1] > 16000000 || max($info[0], $info[1]) > 8000) {
        throw new RuntimeException('รูปมีความละเอียดสูงเกินไป กรุณาย่อรูปให้ไม่เกิน 16 ล้านพิกเซล และด้านละ 8,000 พิกเซล');
    }
    $source = @imagecreatefromstring(file_get_contents($path));
    if (!$source) throw new RuntimeException('ไม่สามารถอ่านรูปนี้ได้ กรุณาเลือกรูปใหม่');
    // Re-encode pixels to remove metadata and any extra content from the upload.
    $scale = min(1, 512 / max($info[0], $info[1]));
    $width = max(1, (int) round($info[0] * $scale));
    $height = max(1, (int) round($info[1] * $scale));
    $thumbnail = imagecreatetruecolor($width, $height);
    imagefill($thumbnail, 0, 0, imagecolorallocate($thumbnail, 255, 255, 255));
    imagecopyresampled($thumbnail, $source, 0, 0, 0, 0, $width, $height, $info[0], $info[1]);
    imagedestroy($source);
    $directory = __DIR__ . '/../uploads';
    $filename = 'profile_' . bin2hex(random_bytes(16)) . '.jpg';
    try {
        if (!is_dir($directory) && !mkdir($directory, 0755, true) && !is_dir($directory)) {
            throw new RuntimeException('ไม่สามารถจัดเก็บรูปได้ กรุณาลองใหม่อีกครั้ง');
        }
        if (!imagejpeg($thumbnail, $directory . '/' . $filename, 88)) {
            @unlink($directory . '/' . $filename);
            throw new RuntimeException('ไม่สามารถบันทึกรูปได้ กรุณาลองใหม่อีกครั้ง');
        }
    } finally {
        imagedestroy($thumbnail);
    }
    return '../uploads/' . $filename;
}

function profile_photo_delete(?string $url): void
{
    // Only remove files generated by this uploader, never arbitrary stored paths.
    if ($url && preg_match('~^\.\./uploads/(profile_[a-f0-9]{32}\.jpg)$~D', $url, $matches)) {
        $path = __DIR__ . '/../uploads/' . $matches[1];
        if (is_file($path)) @unlink($path);
    }
}
