<?php if (!isset($conn, $error)) { http_response_code(404); exit; } ?>
<!doctype html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>เข้าสู่ระบบเจ้าหน้าที่และผู้ดูแลระบบ · ระบบยืมคืนสิ่งของวัด</title><link rel="stylesheet" href="../bootstrap-5.0.2-dist/css/bootstrap.min.css"><link rel="stylesheet" href="../assets/css/auth.css"><?php require __DIR__ . '/theme.php'; ?><link rel="stylesheet" href="../assets/css/login-background.css?v=4"></head>
<body class="auth-page auth-login-page"><header class="auth-header"><a class="auth-brand" href="../index.php"><span class="auth-brand-mark" aria-hidden="true">↔</span><span>ระบบยืมคืนสิ่งของวัด<small>TEMPLE BORROWING SERVICE</small></span></a><a class="auth-back" href="../index.php">← กลับหน้าหลัก</a></header>
<main class="auth-layout">
<section class="auth-card" aria-labelledby="staffTitle"><span class="auth-staff-tag">เจ้าหน้าที่ / ผู้ดูแลระบบ</span><h2 id="staffTitle">ยินดีต้อนรับกลับ</h2><p class="auth-intro">เข้าสู่ระบบด้วยชื่อผู้ใช้และรหัสผ่านของเจ้าหน้าที่หรือผู้ดูแลระบบ</p>
<?php if ($error): ?><div class="auth-error" role="alert" tabindex="-1" data-auth-error><strong>เข้าสู่ระบบไม่สำเร็จ</strong><br><?= app_escape($error) ?></div><?php endif; ?>
<form method="post" class="auth-login-fields"><input type="hidden" name="csrf_token" value="<?= csrf_token() ?>">
<div><label for="staffUsername" class="form-label">ชื่อผู้ใช้</label><input id="staffUsername" type="text" name="username" class="form-control" value="<?= app_escape(is_string($_POST['username'] ?? null) ? $_POST['username'] : '') ?>" maxlength="50" autocomplete="username" placeholder="กรอกชื่อผู้ใช้ของคุณ" required></div>
<div><label for="staffPassword" class="form-label">รหัสผ่าน</label><div class="auth-secret"><input id="staffPassword" name="password" type="password" class="form-control" autocomplete="current-password" placeholder="กรอกรหัสผ่าน" data-secret-label="รหัสผ่าน" required><button type="button" class="auth-reveal" data-password-toggle="staffPassword" aria-controls="staffPassword" aria-pressed="false" aria-label="แสดงรหัสผ่าน">แสดง</button></div></div>
<button type="submit" name="login" value="1" class="auth-submit">เข้าสู่ระบบ →</button></form>
<div class="auth-support"><strong>ลืมรหัสผ่านหรือเข้าสู่ระบบไม่ได้?</strong>กรุณาติดต่อผู้ดูแลระบบของวัดเพื่อขอความช่วยเหลือ</div><p class="text-center mt-4 mb-0"><a class="auth-link" href="../user/index.php">เป็นผู้ยืม? ไปหน้าเข้าสู่ระบบผู้ยืม</a></p>
</section></main><footer class="auth-footnote">ยืมอย่างใส่ใจ คืนให้ครบ เพื่อให้ชุมชนได้ใช้ร่วมกัน</footer><script src="../assets/js/auth.js?v=3" defer></script></body></html>
